/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FyCard: typeof import('fuyu-comp')['fyCard']
    FyConfigProvider: typeof import('fuyu-comp')['fyConfigProvider']
    FyList: typeof import('fuyu-comp')['fyList']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
